 # 1. Create a 1D array of 20 sequential integers and reshape it into a 4x5 matrix.

In [2]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(x.shape)
y= x.reshape(4, 5)
print(y.shape)

(20,)
(4, 5)


# Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

In [14]:
print(np.arange(22, 71, 2))

[22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68
 70]


## 3. Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

In [18]:
print(np.arange(21, 72, 2))

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


## Generate an array of 15 random integers and sort it in ascending order.

In [30]:



x =np.arange(0, 16, 1)
y=np.sort(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## 5. Create a 1D array of zeros of length 10 and set the 5th element to 1.

In [31]:
x=np.array([0,0,0,0,0,0,0,0,0,0])
x[5]=1
print(x)

[0 0 0 0 0 1 0 0 0 0]


## 6. Find the unique elements in a given array [1, 2, 2, 3, 4, 4, 5].

In [33]:
x=np.array([1, 2, 2, 3, 4, 4, 5])
y=np.unique(x)
print(y)

[1 2 3 4 5]


## 7. Create an array with values ranging from 0 to 10 and reverse the array.

In [40]:
x=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(x)
y= x[::-1]
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


## 8. Given a list of birds and their corresponding age, calculate:
a. the mean age of the Crane bird (rounded off to 2 decimal points)
b. find the name of the oldest bird in the list
birds = ['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers',
'Cranes', 'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [59]:
birds = np.array(['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
boolean_array_mean = np.isin(birds, ['Cranes'])
crane_array=age[boolean_array]
mean_value=np.mean(crane_array)
sortedArray=np.sort(age)
highest_age=sortedArray[-1]
boolean_array_highest_array=  np.isin(age, [highest_age])
print(birds[boolean_array_highest_array])


['plovers' 'spoonbills']


## 9. Given a 2d array, write a program to return a subarray such that the subarray consists of the
elements from:
a. the second to the fourth row of the original array,
b. the elements in these rows should be from the last three columns of the
corresponding rows of the original array,
c. the rows should be in reversed order.

In [90]:
x=np.array([[1,2,3,99],[4,5,6,98],[7,8,9,97],[10,11,12,95]])
print(x[1:4,])
print(x[:,-3:])
print(x[::-1])


[[ 4  5  6 98]
 [ 7  8  9 97]
 [10 11 12 95]]
[[ 2  3 99]
 [ 5  6 98]
 [ 8  9 97]
 [11 12 95]]
[[10 11 12 95]
 [ 7  8  9 97]
 [ 4  5  6 98]
 [ 1  2  3 99]]


## 1. Create a 4x4 matrix and replace all elements on its diagonal with 7.

In [102]:
k=np.array([[1,2,3,4],[5,6,17,8],[10,11,12,13],[14,15,16,17]])
np.fill_diagonal(k, 7)
print(k)

[[ 7  2  3  4]
 [ 5  7 17  8]
 [10 11  7 13]
 [14 15 16  7]]


## 2. Given two arrays of the same size, compute their element-wise product.

In [105]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
c=a*b
print(c)

[ 1  4  9 16]


## 3. Create a random 6x6 matrix and compute the mean and standard deviation of its elements.

In [7]:
x=np.random.randint(36,size=(36))
y=x.reshape(6,6)
print(np.mean(y))
print(np.std(y))



14.805555555555555
10.076979939017345


# 4. Stack two arrays vertically and horizontally (use vstack and hstack).

In [14]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b))
     )

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4 1 2 3 4]


In [23]:
#Create a 1D array of 50 random floats between 0 and 1, and count how many values are
#greater than 0.5.
a=np.random.rand(50)
print(len(a[a[:]>0.5]))

26


In [28]:
birds = np.array(['spoonbills', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'plovers', 'plovers', 'Cranes', 'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
matrix=np.column_stack((birds,age))
matrix=matrix[matrix[:,1].argsort()]
print(matrix)

[['plovers' '1.5']
 ['plovers' '2.0']
 ['plovers' '3.0']
 ['plovers' '3.5']
 ['plovers' '3.5']
 ['Cranes' '4.0']
 ['spoonbills' '5.5']
 ['Cranes' '5.5']
 ['plovers' '6.0']
 ['spoonbills' '6.0']]


In [32]:
# 7. Given the shape of an array and a range, Return an array of specified shape, consisting of
# random integers from "discrete uniform" distribution, in given range [low, high].
# Note: high is inclusive in range.
# Input Format:
# o Input has two lines.
# o First line contains the shape of the array.
# o Second line contains the range (low, high).
# Output Format: A NumPy array


shape=(3,4)
low,high=100,200
a=np.random.randint(low,high+1,size=shape)
print(a)

[[124 107 189 148]
 [179 198 100 177]
 [125 172 136 101]]


In [44]:
# 1. Create a 10x10 matrix with random integers and find the indices of the top 3 maximum
# values.
# o
# Concepts: Matrix generation, indexing with conditions.
a=np.random.randint(100,size=(10,10))
flatten_array=a.flatten()
b=flatten_array.argsort()[-3:]
print(b)

[38 60  3]


In [ ]:
# 2. Solve a system of three linear equations using NumPy’s linalg.solve() function.
# o
# Concepts: Linear algebra, system of equations.

In [47]:
coeffient_matrix=np.array([[1,2],[2,1]])
constant_matrix=np.array([1,2])
np.linalg.solve(coeffient_matrix,constant_matrix) 

array([1., 0.])

In [50]:
a=np.random.randint(64,size=(8,8))

b,c=np.linalg.eig(a)
print(b)
print(c)

[255.62311174 +0.j          57.11748942 +0.j
 -34.72541818 +0.j         -20.09486592+22.41821303j
 -20.09486592-22.41821303j  12.51066229+30.78146668j
  12.51066229-30.78146668j  23.15322428 +0.j        ]
[[ 0.3682257 +0.j          0.31570159+0.j         -0.2486123 +0.j
   0.40172466-0.04277789j  0.40172466+0.04277789j  0.2515637 +0.21133397j
   0.2515637 -0.21133397j -0.49394626+0.j        ]
 [ 0.31643965+0.j         -0.37037749+0.j         -0.54103535+0.j
   0.42744636+0.10820058j  0.42744636-0.10820058j -0.07352296-0.4198504j
  -0.07352296+0.4198504j   0.12890572+0.j        ]
 [ 0.2861055 +0.j         -0.31403034+0.j          0.02199174+0.j
  -0.39455002-0.07548126j -0.39455002+0.07548126j -0.19818535+0.3813627j
  -0.19818535-0.3813627j   0.52958623+0.j        ]
 [ 0.28872357+0.j          0.57500663+0.j         -0.15641389+0.j
   0.11474236+0.12447962j  0.11474236-0.12447962j -0.14076403+0.02040424j
  -0.14076403-0.02040424j  0.24161056+0.j        ]
 [ 0.2876062 +0.j          0.0278